runtime: nodejs16  # Adjust runtime version based on your Node.js version

env: flex  # Use the flexible environment for more control

service: your-service-name  # Replace with your desired service name

# Install dependencies during build
build:
  commands:
    - npm install
    # Replace with your Prisma schema path
    - npx prisma generate --prisma-schema=prisma/schema.prisma

# Define environment variables (optional)
env_variables:
  # Replace with your actual database connection details
  DATABASE_URL: "postgres://user:password@host:port/database"

# Expose your server port (replace with your app port)
handlers:
- url: /.*
  script: node server.js

# Specify instances for scaling (optional)
# instances: 1  # Start with 1 instance (adjust based on your needs)

# Configure health checks (optional)
health_checks:
  # App Engine health check path (usually works for Express.js apps)
  readiness_check:
    check_interval_sec: 15  # Check every 15 seconds
    timeout_sec: 5          # Timeout after 5 seconds
    app_engine_health_check: true
