steps:
- name: 'setpermission'
  entrypoint: bash
  args:
  - '-c'
  - set -x && gcloud projects add-iam-policy-binding binaracademy-408514 --member=user:bayuuabdur2903@gmail.com --role=roles/compute.viewer
- name: 'build'
  entrypoint: bash
  args:
  - '-c'
  - set -x && gcloud compute ssh instance-2 --zone=us-central1-a --command='/bin/sh /home/bayuuabdur2903/pull.sh'